import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/assets/css/index.css'
import Header from '@/layouts/main/header'
import Footer from '@/layouts/main/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main className='Main'>{children}</main>
        <Footer />
        </body>
    </html>
  )
}
